language: r
r: bioc-devel
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
      - r-cran-rjava
before_install:
 - export JAVA_HOME=/usr/lib/jvm/java-8-oracle/jre
 - export PATH=$PATH:$JAVA_HOME/bin
 - export LD_LIBRARY_PATH=/usr/lib/jvm/java-8-oracle/lib/amd64:/usr/lib/jvm/java-8-oracle/jre/lib/amd64/server
 - sudo R CMD javareconf
r_packages: gridExtra
bioc_packages:
  - BiocGenerics
  - Biostrings
  - org.Hs.eg.db
  - GOSemSim
  - ChemmineR
  - fmcsR
